services:
  web:
    build:
      context: .
    env_file:
      - .env
    container_name: django_app
    command: sh -c "python manage.py migrate && python manage.py createsuperuser --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUG}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PWD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPERUSER_USERNAME=${SUPERUSER_USERNAME}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
      - SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
    depends_on:
      - db

  db:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PWD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PWD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
