# Generated by Django 5.1.4 on 2025-01-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_chatbot', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
