# Generated by Django 5.1.4 on 2025-01-05 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_chatbot', '0006_user_favorite_foods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_foods',
        ),
    ]
