# Generated by Django 5.1.4 on 2025-01-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_chatbot', '0009_alter_user_favorite_foods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_foods',
            field=models.JSONField(default=dict),
        ),
    ]
